### ISSUE TITLE
Getting issue while using default serializer (Marshall)

### ISSUE THREAD

**Issue by silwalprabin** [EnjoyTech/parallel_workforce#1]
@michaelgpearce 

Thank you for nice contribution, I love this gem.
But got **issue on some data** while using default Marshall serializer. Details are explained below::

I am defining Job as::
```
# Job definition
module ParallelWorkforce
  module Job
    class MyParallelJob < SidekiqRails
        sidekiq_options queue: 'default_queue', retry: 0
    end
  end
end
```
I configure Workforce as:
```
# ParallelWorkforce Configuration
ParallelWorkforce.configure do |config|
  config.job_class = ParallelWorkforce::Job::MyParallelJob
  config.serializer = ParallelWorkforce::Serializer::Marshal.new
  # config.serializer = ParallelWorkforce::Custom::Serializer::Json.new
  config.redis_connector = ParallelWorkforce::RedisConnector::SidekiqRedisPool.new
end
```

I am calling ParallelWorkforce as::
```
# See below cases (CaseI and CaseII) for definition of params_list
parallel_results = ParallelWorkforce.perform_all(  actor_classes: Array.new(params_list.size) { 																				 
  										MyAsyncParamsRunner 
										}, 
										actor_args_array: params_list          
										) 
myresults = parallel_results.flatten
```

```
Case I: Working Fine
params_list = [{ name: "Prabin", id: 124, args: {}}]
=> ParallelWorkforce run and provide result
```

```
Case II: Getting Error (only change is id 136 instead of 124)
params_list = [{ name: "Prabin", id: 136, args: {}}]
=> ParallelWorkforce does not start and throws error::
Encoding::UndefinedConversionError: "\x88" from ASCII-8BIT to UTF-8
from /Users/prabinsilwal/.rbenv/versions/2.6.3/lib/ruby/2.6.0/json/common.rb:224:in `encode'
Encoding::UndefinedConversionError: "\x88" from ASCII-8BIT to UTF-8
/Users/prabinsilwal/vendor/cache/ruby/2.6.0/gems/json-2.3.0/lib/json/common.rb:225:in `generate'
/Users/prabinsilwal/vendor/cache/ruby/2.6.0/gems/json-2.3.0/lib/json/common.rb:225:in `generate'
/Users/prabinsilwal/vendor/cache/ruby/2.6.0/gems/sidekiq-6.0.7/lib/sidekiq.rb:182:in `dump_json'
/Users/prabinsilwal/vendor/cache/ruby/2.6.0/gems/sidekiq-6.0.7/lib/sidekiq/client.rb:206:in `block in atomic_push'
/Users/prabinsilwal/vendor/cache/ruby/2.6.0/gems/sidekiq-6.0.7/lib/sidekiq/client.rb:204:in `map'
/Users/prabinsilwal/vendor/cache/ruby/2.6.0/gems/sidekiq-6.0.7/lib/sidekiq/client.rb:204:in `atomic_push'
/Users/prabinsilwal/vendor/cache/ruby/2.6.0/gems/sidekiq-6.0.7/lib/sidekiq/client.rb:189:in `block (2 levels) in raw_push'
/Users/prabinsilwal/vendor/cache/ruby/2.6.0/gems/redis-4.1.4/lib/redis.rb:2462:in `block in multi' 
/Users/prabinsilwal/vendor/cache/ruby/2.6.0/gems/redis-4.1.4/lib/redis.rb:51:in `block in synchronize'
/Users/prabinsilwal/.rbenv/versions/2.6.3/lib/ruby/2.6.0/monitor.rb:230:in `mon_synchronize'
/Users/prabinsilwal/vendor/cache/ruby/2.6.0/gems/redis-4.1.4/lib/redis.rb:51:in `synchronize'
/Users/prabinsilwal/vendor/cache/ruby/2.6.0/gems/redis-4.1.4/lib/redis.rb:2455:in `multi'
/Users/prabinsilwal/vendor/cache/ruby/2.6.0/gems/sidekiq-6.0.7/lib/sidekiq/client.rb:188:in `block in raw_push'
/Users/prabinsilwal/vendor/cache/ruby/2.6.0/gems/connection_pool-2.2.3/lib/connection_pool.rb:63:in `block (2 levels) in with'
/Users/prabinsilwal/vendor/cache/ruby/2.6.0/gems/connection_pool-2.2.3/lib/connection_pool.rb:62:in `handle_interrupt'
```

I tried changing to my custom JSON serializer as
```
module Custom
  module Serializer
   class Json
   def serialize(object)
          ::JSON.generate(object)
   end
  def deserialize(string)
          ::JSON.parse(string, {:symbolize_names => true})
  end
 end
end

# used in connfiguration as 
config.serializer = Custom::Serializer::Json.new
```

ParallelWorkfore start to work for data of both case (CaseI & CaseII); But since I am using JSON serializer output I receive is not Ruby object and it's string only.

OUR FINDING:: 
It seems for some data JSON and Marshall are not compatible;
```
Eg1: 
  pry(main)> JSON.dump(Marshal.dump([{ name: "Prabin", id: 124, args: {}}]))
=> "\"\\u0004\\b[\\u0006{\\b:\\tnameI\\\"\\u000bPrabin\\u0006:\\u0006ET:\\u0007idi\\u0001|:\\targs{\\u0000\""

```
```
Eg2:
  pry(main)> JSON.dump(Marshal.dump([{ name: "Prabin", id: 136, args: {}}]))
=> Encoding::UndefinedConversionError: "\x88" from ASCII-8BIT to UTF-8
from /Users/prabinsilwal/Documents/vendor/cache/ruby/2.6.0/gems/json-2.3.0/lib/json/common.rb:224:in `generate'
```
How can we solve this issue?

**Comment by michaelgpearce** [comment]
I recreated this scenario and it worked find with a couple of caveats.

1. I changed `config.serializer = ParallelWorkforce::Serializer::Marshal` to `config.serializer = ParallelWorkforce::Serializer::Marshal.new`. The serializer needs an object instance that defines `serialize` and `deserialize` as defined in the README. If you are going to use the default `Marshal` implementation, there is no need to specify this configuration.
2. I added a queue in my sidekiq.yml named `default_queue`.
3. I created an implementation for `MyAsyncParamsRunner`:
```ruby
class MyAsyncParamsRunner
  attr_reader :name, :id, :args

  def initialize(name:, id:, args:)
    @name = name
    @id = id
    @args = args
  end

  def perform
    [
      "name: #{name}",
      "id: #{id}",
      "args: #{args}",
    ].join("\n")
  end
end
```

This executed with both of these commands from a Rails console:
```ruby
[7] super_samurai (US) development(main)> params_list = [{ name: "Prabin", id: 124, args: {}}]
=> [{:name=>"Prabin", :id=>124, :args=>{}}]
[8] super_samurai (US) development(main)> 
[9] super_samurai (US) development(main)> parallel_results = ParallelWorkforce.perform_all(
[9] super_samurai (US) development(main)*   actor_classes: Array.new(params_list.size) {  
[9] super_samurai (US) development(main)*     MyAsyncParamsRunner     
[9] super_samurai (US) development(main)*   },     
[9] super_samurai (US) development(main)*   actor_args_array: params_list,  
[9] super_samurai (US) development(main)* )   
=> ["name: Prabin\nid: 124\nargs: {}"]
[10] super_samurai (US) development(main)> myresults = parallel_results.flatten
=> ["name: Prabin\nid: 124\nargs: {}"]
```

and

```ruby
[13] super_samurai (US) development(main)> params_list = [{ name: "Prabin", id: 136, args: {}}]
=> [{:name=>"Prabin", :id=>136, :args=>{}}]
[14] super_samurai (US) development(main)> 
[15] super_samurai (US) development(main)> parallel_results = ParallelWorkforce.perform_all(
[15] super_samurai (US) development(main)*   actor_classes: Array.new(params_list.size) {  
[15] super_samurai (US) development(main)*     MyAsyncParamsRunner     
[15] super_samurai (US) development(main)*   },     
[15] super_samurai (US) development(main)*   actor_args_array: params_list,  
[15] super_samurai (US) development(main)* )   
=> ["name: Prabin\nid: 136\nargs: {}"]
[16] super_samurai (US) development(main)> myresults = parallel_results.flatten
=> ["name: Prabin\nid: 136\nargs: {}"]
```

**Comment by silwalprabin** [comment]
> I recreated this scenario and it worked find with a couple of caveats.
> 
> 1. I changed `config.serializer = ParallelWorkforce::Serializer::Marshal` to `config.serializer = ParallelWorkforce::Serializer::Marshal.new`. The serializer needs an object instance that defines `serialize` and `deserialize` as defined in the README. If you are going to use the default `Marshal` implementation, there is no need to specify this configuration.
> 2. I added a queue in my sidekiq.yml named `default_queue`.
> 3. I created an implementation for `MyAsyncParamsRunner`:
> 
> ```ruby
> class MyAsyncParamsRunner
>   attr_reader :name, :id, :args
> 
>   def initialize(name:, id:, args:)
>     @name = name
>     @id = id
>     @args = args
>   end
> 
>   def perform
>     [
>       "name: #{name}",
>       "id: #{id}",
>       "args: #{args}",
>     ].join("\n")
>   end
> end
> ```
> 
> This executed with both of these commands from a Rails console:
> 
> ```ruby
> [7] super_samurai (US) development(main)> params_list = [{ name: "Prabin", id: 124, args: {}}]
> => [{:name=>"Prabin", :id=>124, :args=>{}}]
> [8] super_samurai (US) development(main)> 
> [9] super_samurai (US) development(main)> parallel_results = ParallelWorkforce.perform_all(
> [9] super_samurai (US) development(main)*   actor_classes: Array.new(params_list.size) {  
> [9] super_samurai (US) development(main)*     MyAsyncParamsRunner     
> [9] super_samurai (US) development(main)*   },     
> [9] super_samurai (US) development(main)*   actor_args_array: params_list,  
> [9] super_samurai (US) development(main)* )   
> => ["name: Prabin\nid: 124\nargs: {}"]
> [10] super_samurai (US) development(main)> myresults = parallel_results.flatten
> => ["name: Prabin\nid: 124\nargs: {}"]
> ```
> 
> and
> 
> ```ruby
> [13] super_samurai (US) development(main)> params_list = [{ name: "Prabin", id: 136, args: {}}]
> => [{:name=>"Prabin", :id=>136, :args=>{}}]
> [14] super_samurai (US) development(main)> 
> [15] super_samurai (US) development(main)> parallel_results = ParallelWorkforce.perform_all(
> [15] super_samurai (US) development(main)*   actor_classes: Array.new(params_list.size) {  
> [15] super_samurai (US) development(main)*     MyAsyncParamsRunner     
> [15] super_samurai (US) development(main)*   },     
> [15] super_samurai (US) development(main)*   actor_args_array: params_list,  
> [15] super_samurai (US) development(main)* )   
> => ["name: Prabin\nid: 136\nargs: {}"]
> [16] super_samurai (US) development(main)> myresults = parallel_results.flatten
> => ["name: Prabin\nid: 136\nargs: {}"]
> ```

Thank you for your response.
Actually I tried with no serializer modification (default serializer) 
i.e.  config.serializer = ParallelWorkforce::Serializer::Marshal.new ( I missed new in question ; but I tried with new)
Sorry for misunderstanding; Updated the question. 

I just run code you create and following is result::
[8] pry(main)> params_list = [{ name: "Prabin", id: 136, args: {}}]
=> [{:name=>"Prabin", :id=>136, :args=>{}}]
[9] pry(main)> parallel_results = ParallelWorkforce.perform_all(
[9] pry(main)*   actor_classes: Array.new(params_list.size) {  
[9] pry(main)*     ParallelWorkforce::Task::MyAsyncParamsRunner     
[9] pry(main)*   },       
[9] pry(main)*   actor_args_array: params_list,  
[9] pry(main)* )  
Encoding::UndefinedConversionError: "\x88" from ASCII-8BIT to UTF-8
from /Users/prabinsilwal/Documents/development/vendor/cache/ruby/2.6.0/gems/json-2.3.0/lib/json/common.rb:224:in `generate'
[10] pry(main)> params_list = [{ name: "Prabin", id: 124, args: {}}]
=> [{:name=>"Prabin", :id=>124, :args=>{}}]
[11] pry(main)> parallel_results = ParallelWorkforce.perform_all(
[11] pry(main)*   actor_classes: Array.new(params_list.size) {  
[11] pry(main)*     ParallelWorkforce::Task::MyAsyncParamsRunner     
[11] pry(main)*   },       
[11] pry(main)*   actor_args_array: params_list,  
[11] pry(main)* )  
=> ["name: Prabin\n" + "id: 124\n" + "args: {}"]
[12] pry(main)> 

My environment::
Ruby => $ruby --version
ruby 2.6.3p62 (2019-04-16 revision 67580) [x86_64-darwin19]

Rails => $ bin/rails --version
Rails 5.2.4.3

**Comment by silwalprabin** [comment]
```
[8] pry(main)> params_list = [{ name: "Prabin", id: 136, args: {}}]
=> [{:name=>"Prabin", :id=>136, :args=>{}}]
[9] pry(main)> parallel_results = ParallelWorkforce.perform_all(
[9] pry(main)*   actor_classes: Array.new(params_list.size) {  
[9] pry(main)*     ParallelWorkforce::Task::MyAsyncParamsRunner     
[9] pry(main)*   },       
[9] pry(main)*   actor_args_array: params_list,  
[9] pry(main)* )  
Encoding::UndefinedConversionError: "\x88" from ASCII-8BIT to UTF-8
from /Users/prabinsilwal/Documents/development/insurance/vendor/cache/ruby/2.6.0/gems/json-2.3.0/lib/json/common.rb:224:in `generate'
```

And
```

[10] pry(main)> params_list = [{ name: "Prabin", id: 124, args: {}}]
=> [{:name=>"Prabin", :id=>124, :args=>{}}]
[11] pry(main)> parallel_results = ParallelWorkforce.perform_all(
[11] pry(main)*   actor_classes: Array.new(params_list.size) {  
[11] pry(main)*     ParallelWorkforce::Task::MyAsyncParamsRunner     
[11] pry(main)*   },       
[11] pry(main)*   actor_args_array: params_list,  
[11] pry(main)* )  
=> ["name: Prabin\n" + "id: 124\n" + "args: {}"]
```

**Comment by michaelgpearce** [comment]
I'm on an older version of Ruby and Rails. You may need to debug and submit a Pull Request if there is a problem on a newer version of Ruby or Rails.

```
✔ ~/projects/test [master|⚑ 155] 
00:30 $ ruby --version
ruby 2.4.6p354 (2019-04-01 revision 67394) [x86_64-darwin18]
✔ ~/projects/test [master|⚑ 155] 
00:30 $ bin/rails --version
Rails 5.0.7.2
```

**Comment by silwalprabin** [comment]
It seems related to: 
https://github.com/mperham/sidekiq/issues/3638
which seems sidekiq incompatible rather than ruby.
$ bin/sidekiq --version
Sidekiq 6.0.7

Which sidekiq version you are using?

**Comment by michaelgpearce** [comment]
An older version: `Sidekiq 5.2.5`

**Comment by michaelgpearce** [comment]
It seems you may need to use your `ParallelWorkforce::Custom::Serializer::Json.new` serializer / deserializer.

**Comment by silwalprabin** [comment]
> It seems you may need to use your `ParallelWorkforce::Custom::Serializer::Json.new` serializer / deserializer.

Yes, it works after using JSON Serializer but problem is response we receive must be in plain JSON and we have problem getting custom Ruby object deserialized while using JSON.
Eg::
```
[51] pry(main)> class A
[51] pry(main)*   def initialize(id, name, params)   
[51] pry(main)*     @id = id      
[51] pry(main)*     @name = name      
[51] pry(main)*     @params = params      
[51] pry(main)*   end     
[51] pry(main)* end  
=> :initialize
[52] pry(main)> a = A.new(136, 'Prabin', {})
=> #<A:0x00007fd2006fb1c8 @id=136, @name="Prabin", @params={}>
[53] pry(main)> a.class
=> A
[54] pry(main)> b= JSON.load(JSON.dump(a))
=> "#<A:0x00007fd2006fb1c8>"
[55] pry(main)> b.class
=> String
```

Same with Marshal looks like::
```
[57] pry(main)> class A
[57] pry(main)*   def initialize(id, name, params)   
[57] pry(main)*     @id = id      
[57] pry(main)*     @name = name      
[57] pry(main)*     @params = params      
[57] pry(main)*   end     
[57] pry(main)* end  
=> :initialize
[58] pry(main)> a = A.new(136, 'Prabin', {}) 
=> #<A:0x00007fd203a57fa8 @id=136, @name="Prabin", @params={}>
[59] pry(main)> a.class
=> A
[60] pry(main)> b=Marshal.load(Marshal.dump(a))
=> #<A:0x00007fd2007db160 @id=136, @name="Prabin", @params={}>
[61] pry(main)> b.class
=> A
```

**Comment by michaelgpearce** [comment]
I would suggest making a serializer like:

```ruby
class JsonMarshal
  def serialize(object)
    JSON.dump(value: Marshal.dump(object))
  end

  def deserialize(string)
    Marshal.load(JSON.parse(string)['value'])
  end
end
```

```ruby
JsonMarshal.new.deserialize(JsonMarshal.new.serialize({ name: "Prabin", id: 136, args: {}}))
```
evaluates to
```ruby
{:name=>"Prabin", :id=>136, :args=>{}}
```

**Comment by michaelgpearce** [comment]
@silwalprabin Did this work for you?

**Comment by silwalprabin** [comment]
> @silwalprabin Did this work for you?

Yes. But have 3 concerns:
1. Need to check performance with additional serialization,
2. Using Yajl in place of JSON
3. Is there any security or any reasons why sidekiq enforces to JSON in new version.

Will update when I got answers :)

**Comment by michaelgpearce** [comment]
Performance could be a concern. But if you are in a spot where you want to parallelize to workers in separate processes, hopefully JSON encoding/decoding is not as big of a cost as the work that is being done.

There are security concerns when using the native Ruby marshaling (which you would still be doing with what I proposed). So while it gets around the Sidekiq limitation, it doesn't provide any additional safety. I can understand Sidekiq not wanting to be the "unsafe" layer and forcing the developer to explicitly do unsafe things such as Ruby data marshaling.

**Comment by silwalprabin** [comment]
> Performance could be a concern. But if you are in a spot where you want to parallelize to workers in separate processes, hopefully JSON encoding/decoding is not as big of a cost as the work that is being done.
> 
> There are security concerns when using the native Ruby marshaling (which you would still be doing with what I proposed). So while it gets around the Sidekiq limitation, it doesn't provide any additional safety. I can understand Sidekiq not wanting to be the "unsafe" layer and forcing the developer to explicitly do unsafe things such as Ruby data marshaling.

Thank you @michaelgpearce 👍 :) 
Since default Marshal is not supported on new environment; Shall I make PR to use JSON/JsonMarshal as default serializer?

**Comment by michaelgpearce** [comment]
> Since default Marshal is not supported on new environment; Shall I make PR to use JSON/JsonMarshal as default serializer?

I'd love a PR.

**Comment by michaelgpearce** [comment]
See https://github.com/EnjoyTech/parallel_workforce/pull/4
